# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Prototype Triton language frontend backed by TVM TIRX."""

from .contracts import (
    TritonTVMContract,
    get_triton_tvm_contract,
    validate_attention_llama_causal_prefill_contract,
    validate_attention_vit_full_contract,
    normalize_triton_tvm_contract,
    validate_pointwise_grid2d_static_contract,
    validate_vision_conv2d_contract,
    validate_cuda_minimal_contract,
    validate_cuda_pointwise_flat_contract,
    validate_matmul_minimal_contract,
    validate_masked_softmax_row_contract,
    validate_norm_single_row_contract,
    validate_norm_row_contract,
    validate_pointwise_flat_contract,
    validate_pointwise_minimal_contract,
    validate_reduction_minimal_contract,
    validate_row_reduction_contract,
    validate_softmax_row_contract,
    validate_triton_tvm_contract,
)
from .attention import (
    ATTENTION_CONTRACT_LLAMA_CAUSAL_PREFILL,
    ATTENTION_IMPLEMENTATION_KIND_NATIVE_DECOMPOSED,
    ATTENTION_PROVIDER_NATIVE_DECOMPOSED,
    ATTENTION_RUNTIME_KIND_NATIVE_DECOMPOSED,
    AttentionSemantics,
    TargetAttentionDecision,
    TargetAttentionPolicy,
    build_attention_sdpa_tirx_source,
    build_native_decomposed_attention_tirx_source,
    extract_attention_semantics_from_wrapper_sdpa,
    register_python_torch_attention_sdpa,
)
from .errors import (
    TritonTVMContractError,
    TritonTVMError,
    UnsupportedContractError,
    UnsupportedStreamError,
    UnsupportedTTIROpError,
    UnsupportedTargetPolicyError,
)
from .frontend import TTIRArtifact, lower_to_ttir
from .matmul import (
    MATMUL_PERF_ENVELOPE_ID,
    MATMUL_SCHEDULE_REGISTRY_VERSION,
    EXTERN_GEMM_PROVIDER_NATIVE_TVM,
    GENERATED_REAL_TL_DOT_BRIDGE_SOURCE_KIND,
    M129_ROW_THREADED_WRAPPER_MATMUL_SCHEDULE_ID,
    SIMT_TIR_MATMUL_SCHEDULE_ID,
    TENSORCORE_TIR_MATMUL_SCHEDULE_ID,
    MatmulSemantics,
    MatmulScheduleCandidate,
    TargetMatmulDecision,
    TargetMatmulPolicy,
    build_extern_addmm_bias_tirx_source,
    build_native_wrapper_matmul_tirx_source,
    build_matmul_tune_key_payload,
    extract_matmul_semantics_from_wrapper_extern_addmm,
    is_m12_vit_native_wrapper_matmul_scope,
    matmul_schedule_candidate_ids,
    matmul_schedule_candidate_records,
    register_python_torch_extern_addmm_bias,
    register_python_torch_extern_gemm,
)
from .vision import (
    M11_GRID_FAMILIES,
    M11_GRID2D_ARTIFACT_READY,
    M11_GRID2D_IMPLEMENTATION_KIND_NATIVE_TVM,
    M11_GRID2D_PROVIDER_NATIVE_TVM,
    M11_GRID2D_READINESS_VERSION,
    M11_GRID2D_RUNTIME_READY,
    M11_GRID_FAMILY_BN_SILU_FUSION,
    M11_GRID_FAMILY_CONCAT_SPLIT,
    M11_GRID_FAMILY_CONV_ADJACENT_POINTWISE,
    M11_GRID_FAMILY_OTHER_MULTIDIM_POINTWISE,
    M11_GRID_FAMILY_POOL_OR_SOFTMAX,
    M11_GRID_FAMILY_YOLO_DECODE_POSTPROCESS,
    M11_GRID_REPORT_FIELDS,
    M11_GRID_STATUS_CLASSIFIED,
    M11_GRID_TAXONOMY_VERSION,
    VISION_CONTRACT_CONV2D_1X1_NCHW_STATIC,
    VISION_CONTRACT_CONV2D_NCHW_STATIC,
    VISION_CONTRACT_DEPTHWISE_CONV2D_NCHW_STATIC,
    VISION_CONTRACT_GROUPED_CONV2D_NCHW_STATIC,
    VISION_CONTRACT_POINTWISE_GRID2D_STATIC,
    VISION_EXTERN_PACKED_FUNC,
    VISION_M11_4_INTERFACE_STATUS,
    VISION_M11_5_CORPUS_DIFF_BASELINE_ID,
    VISION_M11_5_HARDENING_STATUS,
    VISION_M11_5_RUNTIME_SCOPE_STATUS,
    VISION_M11_6_CORPUS_DIFF_BASELINE_ID,
    VISION_M11_6_INTERFACE_STATUS,
    VISION_M11_6_RUNTIME_SCOPE_STATUS,
    VISION_M11_7_CORPUS_DIFF_BASELINE_ID,
    VISION_M11_7_INTERFACE_STATUS,
    VISION_M11_7_RUNTIME_SCOPE_STATUS,
    VISION_IMPLEMENTATION_KIND_NATIVE_TVM_CONV2D,
    VISION_PROVIDER_DEVICE_TORCH_CUDA,
    VISION_PROVIDER_NATIVE_TVM_CONV2D,
    VISION_PROVIDER_PYTHON_TORCH_HOST_STAGED,
    TargetVisionDecision,
    TargetVisionPolicy,
    VisionConv2DSemantics,
    VisionGrid2DPointwiseSemantics,
    build_extern_conv2d_tirx_source,
    build_native_grid2d_pointwise_tirx_source,
    classify_m11_captured_grid_record,
    extract_vision_conv2d_semantics_from_wrapper_extern,
    is_m11_7_device_conv2d_runtime_scope,
    is_m11_6_static_conv2d_runtime_scope,
    register_device_torch_cuda_extern_conv2d,
    register_python_torch_extern_conv2d,
)
from .passes import M129OptimizeNativeWrapperMatmul, ValidateTritonKernelTIR
from .runtime import TritonTVMArtifact, build_triton_tvm
from .translator import TritonTVMMeta, translate_ttir

__all__ = [
    "TTIRArtifact",
    "MATMUL_PERF_ENVELOPE_ID",
    "MATMUL_SCHEDULE_REGISTRY_VERSION",
    "EXTERN_GEMM_PROVIDER_NATIVE_TVM",
    "GENERATED_REAL_TL_DOT_BRIDGE_SOURCE_KIND",
    "M129_ROW_THREADED_WRAPPER_MATMUL_SCHEDULE_ID",
    "AttentionSemantics",
    "MatmulSemantics",
    "MatmulScheduleCandidate",
    "VisionConv2DSemantics",
    "VisionGrid2DPointwiseSemantics",
    "SIMT_TIR_MATMUL_SCHEDULE_ID",
    "TENSORCORE_TIR_MATMUL_SCHEDULE_ID",
    "ATTENTION_IMPLEMENTATION_KIND_NATIVE_DECOMPOSED",
    "ATTENTION_CONTRACT_LLAMA_CAUSAL_PREFILL",
    "ATTENTION_PROVIDER_NATIVE_DECOMPOSED",
    "ATTENTION_RUNTIME_KIND_NATIVE_DECOMPOSED",
    "M11_GRID_FAMILIES",
    "M11_GRID2D_ARTIFACT_READY",
    "M11_GRID2D_IMPLEMENTATION_KIND_NATIVE_TVM",
    "M11_GRID2D_PROVIDER_NATIVE_TVM",
    "M11_GRID2D_READINESS_VERSION",
    "M11_GRID2D_RUNTIME_READY",
    "M11_GRID_FAMILY_BN_SILU_FUSION",
    "M11_GRID_FAMILY_CONCAT_SPLIT",
    "M11_GRID_FAMILY_CONV_ADJACENT_POINTWISE",
    "M11_GRID_FAMILY_OTHER_MULTIDIM_POINTWISE",
    "M11_GRID_FAMILY_POOL_OR_SOFTMAX",
    "M11_GRID_FAMILY_YOLO_DECODE_POSTPROCESS",
    "M11_GRID_REPORT_FIELDS",
    "M11_GRID_STATUS_CLASSIFIED",
    "M11_GRID_TAXONOMY_VERSION",
    "VISION_CONTRACT_CONV2D_NCHW_STATIC",
    "VISION_CONTRACT_CONV2D_1X1_NCHW_STATIC",
    "VISION_CONTRACT_DEPTHWISE_CONV2D_NCHW_STATIC",
    "VISION_CONTRACT_GROUPED_CONV2D_NCHW_STATIC",
    "VISION_CONTRACT_POINTWISE_GRID2D_STATIC",
    "VISION_EXTERN_PACKED_FUNC",
    "VISION_IMPLEMENTATION_KIND_NATIVE_TVM_CONV2D",
    "VISION_M11_4_INTERFACE_STATUS",
    "VISION_M11_5_CORPUS_DIFF_BASELINE_ID",
    "VISION_M11_5_HARDENING_STATUS",
    "VISION_M11_5_RUNTIME_SCOPE_STATUS",
    "VISION_M11_6_CORPUS_DIFF_BASELINE_ID",
    "VISION_M11_6_INTERFACE_STATUS",
    "VISION_M11_6_RUNTIME_SCOPE_STATUS",
    "VISION_M11_7_CORPUS_DIFF_BASELINE_ID",
    "VISION_M11_7_INTERFACE_STATUS",
    "VISION_M11_7_RUNTIME_SCOPE_STATUS",
    "VISION_PROVIDER_DEVICE_TORCH_CUDA",
    "VISION_PROVIDER_NATIVE_TVM_CONV2D",
    "VISION_PROVIDER_PYTHON_TORCH_HOST_STAGED",
    "TargetAttentionDecision",
    "TargetAttentionPolicy",
    "TargetMatmulDecision",
    "TargetMatmulPolicy",
    "TargetVisionDecision",
    "TargetVisionPolicy",
    "TritonTVMArtifact",
    "TritonTVMContract",
    "TritonTVMContractError",
    "TritonTVMError",
    "TritonTVMMeta",
    "UnsupportedContractError",
    "UnsupportedStreamError",
    "UnsupportedTTIROpError",
    "UnsupportedTargetPolicyError",
    "M129OptimizeNativeWrapperMatmul",
    "ValidateTritonKernelTIR",
    "build_extern_addmm_bias_tirx_source",
    "build_native_wrapper_matmul_tirx_source",
    "build_extern_conv2d_tirx_source",
    "build_native_grid2d_pointwise_tirx_source",
    "build_attention_sdpa_tirx_source",
    "build_native_decomposed_attention_tirx_source",
    "build_triton_tvm",
    "build_matmul_tune_key_payload",
    "classify_m11_captured_grid_record",
    "extract_matmul_semantics_from_wrapper_extern_addmm",
    "extract_attention_semantics_from_wrapper_sdpa",
    "extract_vision_conv2d_semantics_from_wrapper_extern",
    "get_triton_tvm_contract",
    "lower_to_ttir",
    "matmul_schedule_candidate_ids",
    "matmul_schedule_candidate_records",
    "normalize_triton_tvm_contract",
    "is_m11_6_static_conv2d_runtime_scope",
    "is_m11_7_device_conv2d_runtime_scope",
    "is_m12_vit_native_wrapper_matmul_scope",
    "register_python_torch_extern_addmm_bias",
    "register_python_torch_attention_sdpa",
    "register_device_torch_cuda_extern_conv2d",
    "register_python_torch_extern_conv2d",
    "register_python_torch_extern_gemm",
    "translate_ttir",
    "validate_attention_vit_full_contract",
    "validate_attention_llama_causal_prefill_contract",
    "validate_pointwise_grid2d_static_contract",
    "validate_vision_conv2d_contract",
    "validate_matmul_minimal_contract",
    "validate_masked_softmax_row_contract",
    "validate_norm_single_row_contract",
    "validate_norm_row_contract",
    "validate_pointwise_flat_contract",
    "validate_pointwise_minimal_contract",
    "validate_reduction_minimal_contract",
    "validate_row_reduction_contract",
    "validate_softmax_row_contract",
    "validate_triton_tvm_contract",
]
