# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""TorchInductor pointwise TTIR audit helpers.

M3 is an offline coverage audit.  It collects Triton kernels generated by
TorchInductor, lowers them to TTIR, summarizes the TTIR surface area, and tries
the existing pointwise translator only to classify current gaps.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import importlib.util
import json
import tempfile
import textwrap
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .errors import (
    TritonTVMContractError,
    UnsupportedContractError,
    UnsupportedTTIROpError,
    UnsupportedTargetPolicyError,
)
from .frontend import TTIRArtifact, lower_to_ttir
from .op_graph import NormalizedTTIROpGraph
from .translator import translate_ttir
from .ttir import TTIRReader


@dataclass(frozen=True)
class InductorTritonSource:
    """A Triton kernel source block extracted from an Inductor wrapper."""

    case_name: str
    kernel_name: str
    source: str
    device_str: str = "cuda"
    wrapper_path: str = ""


@dataclass(frozen=True)
class InductorKernel:
    """Loaded Inductor Triton kernel and the metadata needed for TTIR lowering."""

    case_name: str
    kernel_name: str
    source: str
    device_str: str
    fn: Any
    signature: dict[str, str]
    constexprs: dict[str, Any]
    attrs: Any
    triton_meta: dict[str, Any]
    inductor_meta: dict[str, Any]
    size_hints: dict[str, Any]


@dataclass(frozen=True)
class _BuiltinCase:
    name: str
    fn: Any
    make_args: Any


def _builtin_add(x, y):
    return x + y


def _builtin_add_mul(x, y):
    return x + y * 2.0


def _builtin_three_input_chain(x, y, z):
    return x * 2.0 + y - z


def _builtin_scalar_alpha(x):
    return x + 2.5


def _builtin_two_scalars(x):
    return x * 2.5 + 1.25


def _builtin_relu_add(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.relu(x) + y


def _builtin_sigmoid_mul(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sigmoid(x) * y


def _builtin_tanh_shift(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.tanh(x) + 1.0


def _builtin_exp_log_abs(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.exp(torch.log(torch.abs(x) + 1.0))


def _builtin_sin_cos(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sin(x) + torch.cos(y)


def _builtin_where_cmp(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.where(x > y, x, y)


def _builtin_clamp_add(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.clamp(x, -0.5, 0.5) + y


def _builtin_reciprocal_abs(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.reciprocal(torch.abs(x) + 1.0)


def _builtin_sqrt_rsqrt(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sqrt(torch.abs(x) + 1.0) + torch.rsqrt(torch.abs(y) + 1.0)


def _builtin_pow2_add(x, y):
    return x * x + y


def _builtin_fp16_add(x, y):
    return x + y


def _builtin_bf16_add(x, y):
    return x + y


def _builtin_int32_add(x, y):
    return x + y


def _builtin_bool_mask(x, y):
    return (x > 0) & (y > 0)


def _builtin_broadcast_row(x, y):
    return x + y


def _builtin_broadcast_col(x, y):
    return x + y


def _builtin_tuple_two_outputs(x, y):
    return x + y, x - y


def _builtin_strided_input(x, y):
    return x[::2] + y


def _builtin_slice_even(x):
    return x[::2] * 2.0


def extract_inductor_triton_sources(
    wrapper_source: str,
    *,
    case_name: str = "",
    wrapper_path: str = "",
) -> list[InductorTritonSource]:
    """Extract ``async_compile.triton(name, source, ...)`` calls from wrapper code."""
    tree = ast.parse(wrapper_source)
    sources: list[InductorTritonSource] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not _is_triton_compile_call(node):
            continue
        if len(node.args) < 2:
            continue
        kernel_name = _literal_string(node.args[0])
        source = _literal_string(node.args[1])
        if not kernel_name or not source:
            continue
        device_str = "cuda"
        for keyword in node.keywords:
            if keyword.arg == "device_str":
                device_str = _literal_string(keyword.value) or device_str
        sources.append(
            InductorTritonSource(
                case_name=case_name or kernel_name,
                kernel_name=kernel_name,
                source=source,
                device_str=device_str,
                wrapper_path=wrapper_path,
            )
        )
    return sources


def load_inductor_kernel(
    source: InductorTritonSource | str,
    *,
    kernel_name: str | None = None,
    case_name: str = "",
    device_str: str = "cuda",
) -> InductorKernel:
    """Load an Inductor Triton source block through PyTorch's ``PyCodeCache``."""
    if isinstance(source, InductorTritonSource):
        kernel_name = source.kernel_name
        case_name = source.case_name
        device_str = source.device_str
        source_code = source.source
    else:
        source_code = source
        kernel_name = kernel_name or _first_triton_jit_function_name(source_code)
        case_name = case_name or kernel_name

    if not kernel_name:
        raise ValueError("Cannot load Inductor Triton source without a kernel name")

    from torch._inductor.codecache import PyCodeCache  # pylint: disable=import-outside-toplevel

    key, path = PyCodeCache.write(source_code)
    module = PyCodeCache.load_by_key_path(key, path, attrs={})
    kernel = getattr(module, kernel_name)
    triton_meta = dict(getattr(kernel, "triton_meta", {}) or {})
    inductor_meta = dict(getattr(kernel, "inductor_meta", {}) or {})
    configs = list(getattr(kernel, "configs", []) or [])
    constexprs = dict(getattr(configs[0], "kwargs", {}) if configs else {})
    signature = dict(triton_meta.get("signature", {}) or {})
    attrs = None
    if configs and hasattr(kernel, "_create_compile_meta"):
        compile_meta = kernel._create_compile_meta(configs[0])  # pylint: disable=protected-access
        signature = dict(compile_meta.get("signature", signature))
        constexprs = dict(compile_meta.get("constants", constexprs))
        attrs = compile_meta.get("configs", [None])[0]

    return InductorKernel(
        case_name=case_name,
        kernel_name=kernel_name,
        source=source_code,
        device_str=device_str,
        fn=getattr(kernel, "fn", kernel),
        signature=signature,
        constexprs=constexprs,
        attrs=attrs,
        triton_meta=triton_meta,
        inductor_meta=inductor_meta,
        size_hints=dict(getattr(kernel, "size_hints", {}) or {}),
    )


def is_inductor_pointwise_kernel(kernel: InductorKernel) -> bool:
    """Return whether a loaded kernel matches the M3 pointwise audit filter."""
    meta = kernel.inductor_meta
    return (
        "triton_heuristics.pointwise" in kernel.source
        and meta.get("grid_type") == "Grid1D"
        and int(meta.get("num_reduction", 0) or 0) == 0
        and not bool(meta.get("atomic_add_found", False))
    )


def lower_inductor_kernel_to_ttir(
    kernel: InductorKernel,
    *,
    dump_path: str | Path | None = None,
) -> TTIRArtifact:
    """Lower a loaded Inductor Triton kernel to optimized TTIR."""
    if kernel.device_str == "cuda":
        from torch._inductor.runtime import (  # pylint: disable=import-outside-toplevel
            triton_helpers,
        )

        triton_helpers.set_driver_to_gpu()
    return lower_to_ttir(
        kernel.fn,
        kernel.signature,
        kernel.constexprs,
        dump_path=dump_path,
        attrs=kernel.attrs,
    )


def audit_inductor_ttir(
    ttir_or_artifact: str | TTIRArtifact,
    *,
    case_name: str = "",
    kernel_name: str = "",
    source: str = "",
    signature: dict[str, str] | None = None,
    constexprs: dict[str, Any] | None = None,
    contract: str = "pointwise_flat",
) -> dict[str, Any]:
    """Summarize one Inductor TTIR module and classify translator support."""
    if isinstance(ttir_or_artifact, TTIRArtifact):
        ttir = ttir_or_artifact.ttir
        kernel_name = kernel_name or ttir_or_artifact.kernel_name
        signature = signature or ttir_or_artifact.signature
        constexprs = constexprs or ttir_or_artifact.constexprs
    else:
        ttir = ttir_or_artifact

    record: dict[str, Any] = {
        "case_name": case_name or kernel_name,
        "kernel_name": kernel_name,
        "source_hash": _sha256(source) if source else "",
        "ttir_hash": _sha256(ttir),
        "signature": dict(signature or {}),
        "constexprs": _jsonable(dict(constexprs or {})),
        "unique_ops": [],
        "op_counts": {},
        "types": [],
        "raw_load_store_attrs": [],
        "load_count": 0,
        "store_count": 0,
        "mask_forms": [],
        "indexing_summary": {},
        "translate_status": {"ok": False, "bucket": "not_run"},
    }

    try:
        graph = TTIRReader().read(ttir)
    except Exception as err:  # pylint: disable=broad-except
        record["translate_status"] = _error_status("reader_error", err)
        return record

    record.update(_graph_coverage(graph))
    try:
        translate_ttir(ttir, grid=(1,), contract=contract)
        record["translate_status"] = {"ok": True, "bucket": "translated"}
    except UnsupportedTTIROpError as err:
        record["translate_status"] = _error_status("unsupported_ttir_op", err)
    except (TritonTVMContractError, UnsupportedContractError) as err:
        record["translate_status"] = _error_status("contract_error", err)
    except UnsupportedTargetPolicyError as err:
        record["translate_status"] = _error_status("target_policy_error", err)
    except Exception as err:  # pylint: disable=broad-except
        record["translate_status"] = _error_status("translate_other_error", err)
    return record


def audit_inductor_kernel(
    kernel: InductorKernel,
    *,
    ttir_dir: str | Path | None = None,
    contract: str = "pointwise_flat",
) -> dict[str, Any]:
    """Lower and audit a loaded Inductor pointwise kernel."""
    dump_path = None
    if ttir_dir is not None:
        dump_path = Path(ttir_dir) / f"{_safe_name(kernel.case_name)}_{kernel.kernel_name}.ttir"
    try:
        artifact = lower_inductor_kernel_to_ttir(kernel, dump_path=dump_path)
    except Exception as err:  # pylint: disable=broad-except
        return {
            "case_name": kernel.case_name,
            "kernel_name": kernel.kernel_name,
            "source_hash": _sha256(kernel.source),
            "ttir_hash": "",
            "signature": dict(kernel.signature),
            "constexprs": _jsonable(kernel.constexprs),
            "unique_ops": [],
            "op_counts": {},
            "types": [],
            "raw_load_store_attrs": [],
            "load_count": 0,
            "store_count": 0,
            "mask_forms": [],
            "indexing_summary": {},
            "translate_status": _error_status("lowering_error", err),
        }
    return audit_inductor_ttir(
        artifact,
        case_name=kernel.case_name,
        kernel_name=kernel.kernel_name,
        source=kernel.source,
        signature=kernel.signature,
        constexprs=kernel.constexprs,
        contract=contract,
    )


def run_inductor_audit(
    sources: list[InductorTritonSource],
    *,
    out_dir: str | Path,
    min_kernels: int = 20,
    contract: str = "pointwise_flat",
    extra_errors: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Audit extracted Inductor sources and write kernel, TTIR, and report files."""
    out_path = Path(out_dir)
    kernel_dir = out_path / "kernels"
    ttir_dir = out_path / "ttir"
    kernel_dir.mkdir(parents=True, exist_ok=True)
    ttir_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    filtered: list[dict[str, Any]] = []
    errors = list(extra_errors or [])

    for source in sources:
        kernel_path = kernel_dir / f"{_safe_name(source.case_name)}_{source.kernel_name}.py"
        kernel_path.write_text(source.source, encoding="utf-8")
        try:
            kernel = load_inductor_kernel(source)
        except Exception as err:  # pylint: disable=broad-except
            errors.append(
                {
                    "case_name": source.case_name,
                    "kernel_name": source.kernel_name,
                    "bucket": "load_error",
                    "error_type": type(err).__name__,
                    "message": str(err),
                }
            )
            continue
        if not is_inductor_pointwise_kernel(kernel):
            filtered.append(
                {
                    "case_name": kernel.case_name,
                    "kernel_name": kernel.kernel_name,
                    "grid_type": kernel.inductor_meta.get("grid_type"),
                    "num_reduction": kernel.inductor_meta.get("num_reduction"),
                    "atomic_add_found": kernel.inductor_meta.get("atomic_add_found"),
                }
            )
            continue
        record = audit_inductor_kernel(kernel, ttir_dir=ttir_dir, contract=contract)
        record["kernel_source_path"] = str(kernel_path)
        ttir_path = ttir_dir / f"{_safe_name(kernel.case_name)}_{kernel.kernel_name}.ttir"
        record["ttir_path"] = str(ttir_path)
        records.append(record)

    if len(records) < min_kernels:
        raise RuntimeError(
            f"M3 Inductor audit collected {len(records)} pointwise kernels, "
            f"below required minimum {min_kernels}"
        )

    report = build_audit_report(records, filtered=filtered, errors=errors)
    write_audit_report(report, out_path)
    return report


def build_audit_report(
    kernel_records: list[dict[str, Any]],
    *,
    filtered: list[dict[str, Any]] | None = None,
    errors: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build the JSON-serializable M3 audit report payload."""
    op_histogram: Counter[str] = Counter()
    type_histogram: Counter[str] = Counter()
    bucket_histogram: Counter[str] = Counter()
    for record in kernel_records:
        op_histogram.update(record.get("op_counts", {}))
        type_histogram.update(record.get("types", []))
        status = record.get("translate_status", {})
        bucket_histogram[status.get("bucket", "unknown")] += 1

    return {
        "schema_version": 1,
        "purpose": "m3 inductor pointwise ttir coverage audit",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_kernels": len(kernel_records),
        "translated_kernels": sum(
            1 for record in kernel_records if record.get("translate_status", {}).get("ok")
        ),
        "op_histogram": dict(sorted(op_histogram.items())),
        "type_histogram": dict(sorted(type_histogram.items())),
        "unsupported_buckets": dict(sorted(bucket_histogram.items())),
        "filtered_kernels": list(filtered or []),
        "collection_errors": list(errors or []),
        "kernels": kernel_records,
    }


def write_audit_report(report: dict[str, Any], out_dir: str | Path) -> None:
    """Write ``report.json`` and ``report.md`` for an M3 audit run."""
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    (out_path / "report.json").write_text(
        json.dumps(_jsonable(report), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (out_path / "report.md").write_text(render_audit_markdown(report), encoding="utf-8")


def render_audit_markdown(report: dict[str, Any]) -> str:
    """Render a compact Markdown view of the M3 audit report."""
    lines = [
        "# M3 Inductor Pointwise TTIR Audit",
        "",
        "## Summary",
        "",
        f"- Total pointwise kernels: {report['total_kernels']}",
        f"- Translated by selected translator contract: {report['translated_kernels']}",
        f"- Unsupported buckets: {_format_histogram(report['unsupported_buckets'])}",
        "",
        "## TTIR Op Coverage",
        "",
        "| Op | Count |",
        "|---|---:|",
    ]
    lines.extend(f"| `{op}` | {count} |" for op, count in report["op_histogram"].items())
    lines.extend(
        [
            "",
            "## Type Coverage",
            "",
            "| Type | Count |",
            "|---|---:|",
        ]
    )
    lines.extend(f"| `{ty}` | {count} |" for ty, count in report["type_histogram"].items())
    lines.extend(
        [
            "",
            "## Kernel Status",
            "",
            "| Case | Kernel | Loads | Stores | Status | Message |",
            "|---|---|---:|---:|---|---|",
        ]
    )
    for record in report["kernels"]:
        status = record["translate_status"]
        message = status.get("message", "")
        lines.append(
            "| {case} | `{kernel}` | {loads} | {stores} | {bucket} | {message} |".format(
                case=record["case_name"],
                kernel=record["kernel_name"],
                loads=record["load_count"],
                stores=record["store_count"],
                bucket=status.get("bucket", ""),
                message=_escape_markdown_cell(message[:160]),
            )
        )
    lines.extend(
        [
            "",
            "## M3.5 Priority Gaps",
            "",
            "- Add safe handling for masked `tt.load` without `other` or prove masked-out lanes.",
            "- Extend reader/translator coverage for high-frequency Inductor pointwise ops.",
            "- Add indexing support for broadcast and strided pointwise patterns.",
            "- Keep M3.5 offline-only until these gaps have targeted regression tests.",
            "",
        ]
    )
    return "\n".join(lines)


def collect_builtin_inductor_sources(
    *,
    min_kernels: int = 20,
) -> tuple[list[InductorTritonSource], list[dict[str, Any]]]:
    """Compile the built-in pointwise corpus and collect generated Triton sources."""
    import torch  # pylint: disable=import-outside-toplevel
    import torch._dynamo  # pylint: disable=import-outside-toplevel
    import torch._inductor.config as inductor_config  # pylint: disable=import-outside-toplevel
    from torch._inductor.graph import GraphLowering  # pylint: disable=import-outside-toplevel

    if not torch.cuda.is_available():
        raise RuntimeError("The built-in Inductor corpus requires CUDA")

    old_save_output_code = GraphLowering.save_output_code
    old_fx_graph_cache = inductor_config.fx_graph_cache
    sources: list[InductorTritonSource] = []
    errors: list[dict[str, Any]] = []
    inductor_config.fx_graph_cache = False
    try:
        builtin_module = _load_builtin_corpus_module()
        for case in _builtin_cases(torch, builtin_module):
            captured: list[str] = []
            GraphLowering.save_output_code = captured.append
            try:
                torch._dynamo.reset()
                compiled = torch.compile(case.fn, backend="inductor")
                args = case.make_args(torch)
                with torch.no_grad():
                    compiled(*args)
                torch.cuda.synchronize()
            except Exception as err:  # pylint: disable=broad-except
                errors.append(
                    {
                        "case_name": case.name,
                        "kernel_name": "",
                        "bucket": "compile_error",
                        "error_type": type(err).__name__,
                        "message": str(err),
                    }
                )
            finally:
                GraphLowering.save_output_code = old_save_output_code
            for wrapper_source in captured:
                sources.extend(
                    extract_inductor_triton_sources(wrapper_source, case_name=case.name)
                )
    finally:
        GraphLowering.save_output_code = old_save_output_code
        inductor_config.fx_graph_cache = old_fx_graph_cache
        torch._dynamo.reset()

    if len(sources) < min_kernels:
        errors.append(
            {
                "case_name": "builtin_corpus",
                "kernel_name": "",
                "bucket": "collection_error",
                "error_type": "RuntimeError",
                "message": f"collected {len(sources)} Triton sources below requested {min_kernels}",
            }
        )
    return sources, errors


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for ``python -m tvm.contrib.triton_tvm.inductor``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--builtin-corpus", action="store_true")
    parser.add_argument("--input-dir", type=Path, action="append", default=[])
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--min-kernels", type=int, default=20)
    parser.add_argument("--contract", default="pointwise_flat")
    args = parser.parse_args(argv)

    sources: list[InductorTritonSource] = []
    errors: list[dict[str, Any]] = []
    if args.builtin_corpus:
        builtin_sources, builtin_errors = collect_builtin_inductor_sources(
            min_kernels=args.min_kernels
        )
        sources.extend(builtin_sources)
        errors.extend(builtin_errors)
    for input_dir in args.input_dir:
        sources.extend(_sources_from_input_dir(input_dir))
    if not sources:
        raise RuntimeError("No Inductor Triton sources were collected")

    report = run_inductor_audit(
        sources,
        out_dir=args.out_dir,
        min_kernels=args.min_kernels,
        contract=args.contract,
        extra_errors=errors,
    )
    print(
        "Wrote M3 Inductor audit with "
        f"{report['total_kernels']} kernels to {args.out_dir}"
    )
    return 0


def _sources_from_input_dir(input_dir: Path) -> list[InductorTritonSource]:
    sources: list[InductorTritonSource] = []
    for path in sorted(input_dir.rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        sources.extend(
            extract_inductor_triton_sources(
                text,
                case_name=path.stem,
                wrapper_path=str(path),
            )
        )
    return sources


def _graph_coverage(graph: NormalizedTTIROpGraph) -> dict[str, Any]:
    op_counts = Counter(op.name for op in graph.ops)
    types = sorted(
        {
            param.type.raw
            for param in graph.params
        }
        | {
            ty.raw
            for op in graph.ops
            for ty in op.result_types
        }
    )
    load_store_attrs = []
    for op in graph.ops:
        if op.name in ("tt.load", "tt.store") and op.attrs.get("raw_attrs"):
            load_store_attrs.append(
                {
                    "op": op.name,
                    "raw_attrs": op.attrs.get("raw_attrs", ""),
                    "unknown_attrs": dict(op.attrs.get("unknown_attrs", {}) or {}),
                }
            )
    return {
        "unique_ops": sorted(op_counts),
        "op_counts": dict(sorted(op_counts.items())),
        "types": types,
        "raw_load_store_attrs": load_store_attrs,
        "load_count": op_counts.get("tt.load", 0),
        "store_count": op_counts.get("tt.store", 0),
        "mask_forms": _mask_forms(graph),
        "indexing_summary": _indexing_summary(graph),
    }


def _mask_forms(graph: NormalizedTTIROpGraph) -> list[dict[str, str]]:
    defs = graph.op_by_result()
    forms: list[dict[str, str]] = []
    seen: set[tuple[str, str, str]] = set()
    for op in graph.ops:
        mask = ""
        if op.name == "tt.load" and len(op.operands) >= 2:
            mask = op.operands[1]
        elif op.name == "tt.store" and len(op.operands) >= 3:
            mask = op.operands[2]
        if not mask:
            continue
        mask_def = defs.get(mask)
        key = (op.name, mask, mask_def.raw if mask_def else "")
        if key in seen:
            continue
        seen.add(key)
        forms.append(
            {
                "consumer": op.name,
                "mask": mask,
                "def_op": mask_def.name if mask_def else "",
                "raw": mask_def.raw if mask_def else "",
            }
        )
    return forms


def _indexing_summary(graph: NormalizedTTIROpGraph) -> dict[str, Any]:
    program_id_axes = [
        str(op.attrs.get("axis", ""))
        for op in graph.ops
        if op.name == "tt.get_program_id"
    ]
    addptr_ops = [op for op in graph.ops if op.name == "tt.addptr"]
    return {
        "kind": "flat_or_broadcast_candidate" if addptr_ops else "no_addptr",
        "addptr_count": len(addptr_ops),
        "make_range_count": sum(1 for op in graph.ops if op.name == "tt.make_range"),
        "program_id_axes": sorted(set(program_id_axes)),
        "addptr_operands": [list(op.operands) for op in addptr_ops],
    }


def _load_builtin_corpus_module():
    source = textwrap.dedent(
        """
        import torch

        def m3_add(x, y):
            return x + y

        def m3_add_mul(x, y):
            return x + y * 2.0

        def m3_three_input_chain(x, y, z):
            return x * 2.0 + y - z

        def m3_scalar_alpha(x):
            return x + 2.5

        def m3_two_scalars(x):
            return x * 2.5 + 1.25

        def m3_relu_add(x, y):
            return torch.relu(x) + y

        def m3_sigmoid_mul(x, y):
            return torch.sigmoid(x) * y

        def m3_tanh_shift(x):
            return torch.tanh(x) + 1.0

        def m3_exp_log_abs(x):
            return torch.exp(torch.log(torch.abs(x) + 1.0))

        def m3_sin_cos(x, y):
            return torch.sin(x) + torch.cos(y)

        def m3_where_cmp(x, y):
            return torch.where(x > y, x, y)

        def m3_clamp_add(x, y):
            return torch.clamp(x, -0.5, 0.5) + y

        def m3_reciprocal_abs(x):
            return torch.reciprocal(torch.abs(x) + 1.0)

        def m3_sqrt_rsqrt(x, y):
            return torch.sqrt(torch.abs(x) + 1.0) + torch.rsqrt(torch.abs(y) + 1.0)

        def m3_pow2_add(x, y):
            return x * x + y

        def m3_fp16_add(x, y):
            return x + y

        def m3_bf16_add(x, y):
            return x + y

        def m3_int32_add(x, y):
            return x + y

        def m3_bool_mask(x, y):
            return (x > 0) & (y > 0)

        def m3_broadcast_row(x, y):
            return x + y

        def m3_broadcast_col(x, y):
            return x + y

        def m3_tuple_two_outputs(x, y):
            return x + y, x - y

        def m3_strided_input(x, y):
            return x[::2] + y

        def m3_slice_even(x):
            return x[::2] * 2.0
        """
    )
    path = Path(tempfile.gettempdir()) / "triton_tvm_m3_builtin_corpus.py"
    path.write_text(source, encoding="utf-8")
    spec = importlib.util.spec_from_file_location("triton_tvm_m3_builtin_corpus", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import builtin corpus module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _builtin_cases(torch, module=None) -> list[_BuiltinCase]:
    device = "cuda"

    def rand(shape, dtype=torch.float32):
        return torch.randn(shape, device=device, dtype=dtype)

    def randint(shape):
        return torch.randint(0, 17, shape, device=device, dtype=torch.int32)

    def fn(name: str):
        if module is not None:
            return getattr(module, f"m3_{name}")
        return globals()[f"_builtin_{name}"]

    return [
        _BuiltinCase("add", fn("add"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase("add_mul", fn("add_mul"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase(
            "three_input_chain",
            fn("three_input_chain"),
            lambda _: (rand((257,)), rand((257,)), rand((257,))),
        ),
        _BuiltinCase("scalar_alpha", fn("scalar_alpha"), lambda _: (rand((256,)),)),
        _BuiltinCase("two_scalars", fn("two_scalars"), lambda _: (rand((256,)),)),
        _BuiltinCase(
            "relu_add",
            fn("relu_add"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "sigmoid_mul",
            fn("sigmoid_mul"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase("tanh_shift", fn("tanh_shift"), lambda _: (rand((256,)),)),
        _BuiltinCase(
            "exp_log_abs",
            fn("exp_log_abs"),
            lambda _: (rand((256,)),),
        ),
        _BuiltinCase(
            "sin_cos",
            fn("sin_cos"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "where_cmp",
            fn("where_cmp"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "clamp_add",
            fn("clamp_add"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "reciprocal_abs",
            fn("reciprocal_abs"),
            lambda _: (rand((256,)),),
        ),
        _BuiltinCase(
            "sqrt_rsqrt",
            fn("sqrt_rsqrt"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase("pow2_add", fn("pow2_add"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase(
            "fp16_add",
            fn("fp16_add"),
            lambda _: (rand((256,), torch.float16), rand((256,), torch.float16)),
        ),
        _BuiltinCase(
            "bf16_add",
            fn("bf16_add"),
            lambda _: (rand((256,), torch.bfloat16), rand((256,), torch.bfloat16)),
        ),
        _BuiltinCase("int32_add", fn("int32_add"), lambda _: (randint((256,)), randint((256,)))),
        _BuiltinCase(
            "bool_mask",
            fn("bool_mask"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "broadcast_row",
            fn("broadcast_row"),
            lambda _: (rand((16, 16)), rand((1, 16))),
        ),
        _BuiltinCase(
            "broadcast_col",
            fn("broadcast_col"),
            lambda _: (rand((16, 16)), rand((16, 1))),
        ),
        _BuiltinCase(
            "tuple_two_outputs",
            fn("tuple_two_outputs"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "strided_input",
            fn("strided_input"),
            lambda _: (rand((512,)), rand((256,))),
        ),
        _BuiltinCase("slice_even", fn("slice_even"), lambda _: (rand((512,)),)),
    ]


def _is_triton_compile_call(node: ast.Call) -> bool:
    return isinstance(node.func, ast.Attribute) and node.func.attr == "triton"


def _literal_string(node: ast.AST) -> str:
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError):
        return ""
    return value if isinstance(value, str) else ""


def _first_triton_jit_function_name(source: str) -> str:
    tree = ast.parse(source)
    saw_jit = False
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if any(_decorator_mentions_triton_jit(decorator) for decorator in node.decorator_list):
            return node.name
    return ""


def _decorator_mentions_triton_jit(node: ast.AST) -> bool:
    if isinstance(node, ast.Attribute) and node.attr == "jit":
        return True
    if isinstance(node, ast.Call):
        return _decorator_mentions_triton_jit(node.func)
    return False


def _error_status(bucket: str, err: Exception) -> dict[str, Any]:
    return {
        "ok": False,
        "bucket": bucket,
        "error_type": type(err).__name__,
        "message": str(err),
    }


def _jsonable(value: Any) -> Any:
    try:
        json.dumps(value)
        return value
    except TypeError:
        if isinstance(value, dict):
            return {str(k): _jsonable(v) for k, v in value.items()}
        if isinstance(value, (list, tuple, set, frozenset)):
            return [_jsonable(v) for v in value]
        return repr(value)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _safe_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in name)


def _format_histogram(histogram: dict[str, int]) -> str:
    if not histogram:
        return "none"
    return ", ".join(f"{key}={value}" for key, value in sorted(histogram.items()))


def _escape_markdown_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
