# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""TorchInductor pointwise TTIR audit and experimental hook helpers.

The audit path collects Triton kernels generated by TorchInductor, lowers them
to TTIR, summarizes the TTIR surface area, and classifies support through
canonical Triton TVM contracts.

The M5 hook path is intentionally experimental.  It wraps TorchInductor's
``AsyncCompile.triton`` call site during one ``torch.compile`` invocation and
routes currently-supported pointwise kernels through TVM, with native Triton
fallback for unsupported kernels.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import inspect
import importlib.util
import json
import tempfile
import threading
import textwrap
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .errors import (
    TritonTVMContractError,
    UnsupportedContractError,
    UnsupportedTTIROpError,
    UnsupportedTargetPolicyError,
)
from .frontend import TTIRArtifact, lower_to_ttir
from .indexing import summarize_ttir_indexing
from .op_graph import NormalizedTTIROpGraph
from .reporting import (
    build_capability_report,
    make_report_status,
    render_capability_markdown,
    status_from_exception,
    write_capability_report,
)
from .runtime import TritonTVMArtifact, build_triton_tvm
from .translator import translate_ttir
from .ttir import TTIRReader


_HOOK_LOCK = threading.RLock()
_ACTIVE_HOOK: dict[str, Any] | None = None


@dataclass(frozen=True)
class InductorTritonSource:
    """A Triton kernel source block extracted from an Inductor wrapper."""

    case_name: str
    kernel_name: str
    source: str
    device_str: str = "cuda"
    wrapper_path: str = ""


@dataclass(frozen=True)
class InductorWrapperExternCall:
    """A wrapper-level non-Triton call emitted by TorchInductor."""

    case_name: str
    op_name: str
    op_family: str
    line_no: int
    wrapper_path: str = ""
    source: str = ""


@dataclass(frozen=True)
class InductorKernel:
    """Loaded Inductor Triton kernel and the metadata needed for TTIR lowering."""

    case_name: str
    kernel_name: str
    source: str
    device_str: str
    fn: Any
    signature: dict[str, str]
    constexprs: dict[str, Any]
    attrs: Any
    triton_meta: dict[str, Any]
    inductor_meta: dict[str, Any]
    size_hints: dict[str, Any]


@dataclass(frozen=True)
class TritonTVMInductorConfig:
    """Configuration for the experimental M5 TorchInductor hook.

    This is not a stable ABI.  M5 keeps the surface narrow: only native fallback
    and the existing ``pointwise_flat`` contract are supported.
    """

    fallback: str = "native"
    target: str = "cuda"
    passes: tuple[Any, ...] = ()
    report_dir: str | Path | None = None


@dataclass
class TritonTVMInductorSession:
    """State for one experimental M5 Inductor integration session."""

    config: TritonTVMInductorConfig = field(default_factory=TritonTVMInductorConfig)
    artifacts: dict[str, TritonTVMArtifact] = field(default_factory=dict)
    records: list[dict[str, Any]] = field(default_factory=list)
    graphs: list[dict[str, Any]] = field(default_factory=list)
    collection_errors: list[dict[str, Any]] = field(default_factory=list)
    private_api_guard: dict[str, Any] = field(default_factory=dict)
    counters: Counter = field(default_factory=Counter)
    _active_graphs: list[dict[str, Any]] = field(
        default_factory=list, init=False, repr=False
    )

    def __post_init__(self) -> None:
        if self.config.fallback != "native":
            raise ValueError(
                "M5 Triton TVM Inductor hook only supports fallback='native'"
            )

    def begin_graph(self, *, compile_region_name: str = "") -> dict[str, Any]:
        """Start a graph-level report record for one wrapped Inductor compile."""
        graph = {
            "graph_id": f"graph_{len(self.graphs)}",
            "compile_region_name": compile_region_name,
            "status": "compiling",
            "total_kernels": 0,
            "translated_kernels": 0,
            "native_fallback_kernels": 0,
            "cache_hits": 0,
            "cache_misses": 0,
            "run_count": 0,
            "fallback_reasons": {},
            "kernel_names": [],
            "kernel_record_indices": [],
        }
        self.graphs.append(graph)
        self._active_graphs.append(graph)
        self.counters["graphs_started"] += 1
        return graph

    def end_graph(
        self,
        graph: dict[str, Any],
        *,
        ok: bool,
        err: Exception | None = None,
    ) -> None:
        """Finish a graph-level report record."""
        if self._active_graphs and self._active_graphs[-1] is graph:
            self._active_graphs.pop()
        elif graph in self._active_graphs:
            self._active_graphs.remove(graph)
        graph["status"] = "completed" if ok else "internal_error"
        if err is not None:
            graph["error_type"] = type(err).__name__
            graph["message"] = str(err)
        self.counters["graphs_completed" if ok else "graphs_failed"] += 1
        self.write_report()

    def compile_triton(
        self,
        async_compile,
        original_triton,
        kernel_name: str,
        source_code: str,
        device_str: str = "cuda",
    ):
        """Compile one Inductor Triton kernel or return native fallback.

        ``original_triton`` is the unpatched ``AsyncCompile.triton`` method.  It
        is called only when this prototype cannot produce a TVM-backed kernel.
        """
        source = InductorTritonSource(
            case_name=kernel_name,
            kernel_name=kernel_name,
            source=source_code,
            device_str=device_str,
        )
        try:
            tvm_kernel = self._try_compile_tvm_kernel(
                source,
                async_compile=async_compile,
                original_triton=original_triton,
            )
        except Exception as err:  # pylint: disable=broad-except
            self._record_fallback(source, status_from_exception(err))
            return original_triton(async_compile, kernel_name, source_code, device_str)
        if tvm_kernel is None:
            return original_triton(async_compile, kernel_name, source_code, device_str)
        return tvm_kernel

    def report(self) -> dict[str, Any]:
        """Return the current M5 hook report using the shared capability schema."""
        report = build_capability_report(
            self.records,
            purpose="m5 inductor integration prototype",
            corpus="m5_inductor_hook",
            errors=self.collection_errors,
        )
        report["artifact_cache_size"] = len(self.artifacts)
        report["counters"] = dict(sorted(self.counters.items()))
        report["graph_summary"] = self._graph_summary()
        report["graphs"] = [_jsonable(dict(graph)) for graph in self.graphs]
        report["private_api_guard"] = _jsonable(dict(self.private_api_guard))
        report["runtime_counter_policy"] = _m5_runtime_counter_policy()
        report["report_flush_policy"] = "eager_when_report_dir_set"
        return report

    def write_report(self, out_dir: str | Path | None = None) -> None:
        """Write ``report.json`` and ``report.md`` for the current session."""
        report_dir = out_dir if out_dir is not None else self.config.report_dir
        if report_dir is None:
            return
        write_capability_report(
            self.report(),
            report_dir,
            markdown_title="M5 Inductor Integration Prototype",
            footer_lines=_m5_boundary_lines(),
        )

    def _try_compile_tvm_kernel(
        self,
        source: InductorTritonSource,
        *,
        async_compile,
        original_triton,
    ):
        kernel = load_inductor_kernel(source)
        if not is_inductor_pointwise_kernel(kernel):
            status = make_report_status(
                ok=False,
                bucket="contract_error",
                fallback_reason="unsupported_inductor_kernel",
                message=(
                    "M5 supports only Grid1D non-atomic pointwise Inductor "
                    "kernels through TVM"
                ),
            )
            self._record_fallback(source, status, kernel=kernel)
            return None

        artifact = lower_inductor_kernel_to_ttir(kernel)
        irmod, meta = translate_ttir(
            artifact,
            grid=(1,),
            target=self.config.target,
            contract="pointwise_flat",
        )
        cache_hit = meta.cache_key in self.artifacts
        if cache_hit:
            built = self.artifacts[meta.cache_key]
            self.counters["cache_hits"] += 1
        else:
            built = build_triton_tvm(
                irmod,
                meta,
                passes=self.config.passes,
                target=self.config.target,
            )
            self.artifacts[meta.cache_key] = built
            self.counters["cache_misses"] += 1

        record = self._record_translated(
            kernel=kernel,
            artifact=artifact,
            built=built,
            cache_hit=cache_hit,
        )
        return _TritonTVMInductorKernel(
            session=self,
            record=record,
            artifact=built,
            async_compile=async_compile,
            original_triton=original_triton,
            kernel_name=source.kernel_name,
            source_code=source.source,
            device_str=source.device_str,
        )

    def _record_translated(
        self,
        *,
        kernel: InductorKernel,
        artifact: TTIRArtifact,
        built: TritonTVMArtifact,
        cache_hit: bool,
    ) -> dict[str, Any]:
        try:
            coverage = _graph_coverage(TTIRReader().read(artifact.ttir))
        except Exception:  # pylint: disable=broad-except
            coverage = {}
        record = _base_m5_record(
            kernel_name=kernel.kernel_name,
            source=kernel.source,
            signature=kernel.signature,
            constexprs=kernel.constexprs,
            status=make_report_status(ok=True, bucket="translated"),
        )
        record.update(coverage)
        record.update(
            {
                "ttir_hash": _sha256(artifact.ttir),
                "cache_key": built.meta.cache_key,
                "cache_hit": bool(cache_hit),
                "cache_policy": built.meta.cache_policy,
                "disk_cache_enabled": built.meta.disk_cache_enabled,
                "run_count": 0,
                "native_fallback_count": 0,
            }
        )
        self._attach_record_to_graph(record, translated=True, cache_hit=cache_hit)
        self.records.append(record)
        self.counters["translated"] += 1
        self.write_report()
        return record

    def _record_fallback(
        self,
        source: InductorTritonSource,
        status: dict[str, Any],
        *,
        kernel: InductorKernel | None = None,
    ) -> dict[str, Any]:
        signature = kernel.signature if kernel is not None else {}
        constexprs = kernel.constexprs if kernel is not None else {}
        record = _base_m5_record(
            kernel_name=source.kernel_name,
            source=source.source,
            signature=signature,
            constexprs=constexprs,
            status=status,
        )
        if kernel is not None:
            record.update(
                {
                    "grid_type": kernel.inductor_meta.get("grid_type"),
                    "num_reduction": kernel.inductor_meta.get("num_reduction"),
                    "atomic_add_found": kernel.inductor_meta.get("atomic_add_found"),
                }
            )
        record["native_fallback_count"] = 1
        self._attach_record_to_graph(record, translated=False, cache_hit=False)
        self.records.append(record)
        self.counters["native_fallbacks"] += 1
        self.write_report()
        return record

    def _record_run(self, record: dict[str, Any]) -> None:
        record["run_count"] = int(record.get("run_count", 0)) + 1
        graph = self._graph_by_id(record.get("graph_id", ""))
        if graph is not None:
            graph["run_count"] = int(graph.get("run_count", 0)) + 1
        self.counters["runs"] += 1
        self.write_report()

    def _attach_record_to_graph(
        self,
        record: dict[str, Any],
        *,
        translated: bool,
        cache_hit: bool,
    ) -> None:
        graph = self._current_graph()
        if graph is None:
            return
        record_index = len(self.records)
        record["graph_id"] = graph["graph_id"]
        record["graph_kernel_index"] = len(graph["kernel_names"])
        graph["total_kernels"] += 1
        graph["kernel_names"].append(record["kernel_name"])
        graph["kernel_record_indices"].append(record_index)
        if translated:
            graph["translated_kernels"] += 1
            if cache_hit:
                graph["cache_hits"] += 1
            else:
                graph["cache_misses"] += 1
        else:
            graph["native_fallback_kernels"] += 1
            status = record.get("translate_status", {})
            reason = status.get("fallback_reason") or status.get("bucket", "unknown")
            fallback_reasons = graph["fallback_reasons"]
            fallback_reasons[reason] = int(fallback_reasons.get(reason, 0)) + 1

    def _current_graph(self) -> dict[str, Any] | None:
        return self._active_graphs[-1] if self._active_graphs else None

    def _graph_by_id(self, graph_id: str) -> dict[str, Any] | None:
        if not graph_id:
            return None
        return next(
            (graph for graph in self.graphs if graph["graph_id"] == graph_id),
            None,
        )

    def _record_private_api_guard(self, guard: dict[str, Any]) -> None:
        self.private_api_guard.update(_jsonable(dict(guard)))
        self.private_api_guard["ok"] = True
        self.counters["private_api_guard_checks"] += 1

    def _record_private_api_guard_error(self, err: Exception) -> None:
        status = status_from_exception(err)
        entry = {
            "stage": "private_api_guard",
            "bucket": status["bucket"],
            "fallback_reason": status["fallback_reason"],
            "error_type": status.get("error_type", type(err).__name__),
            "message": status.get("message", str(err)),
        }
        self.collection_errors.append(entry)
        self.private_api_guard = {"ok": False, **entry}
        self.counters["private_api_guard_failures"] += 1
        self.write_report()

    def _graph_summary(self) -> dict[str, Any]:
        return {
            "total_graphs": len(self.graphs),
            "completed_graphs": sum(
                1 for graph in self.graphs if graph["status"] == "completed"
            ),
            "failed_graphs": sum(
                1 for graph in self.graphs if graph["status"] == "internal_error"
            ),
            "total_kernels": sum(
                int(graph.get("total_kernels", 0)) for graph in self.graphs
            ),
            "translated_kernels": sum(
                int(graph.get("translated_kernels", 0)) for graph in self.graphs
            ),
            "native_fallback_kernels": sum(
                int(graph.get("native_fallback_kernels", 0)) for graph in self.graphs
            ),
            "cache_hits": sum(int(graph.get("cache_hits", 0)) for graph in self.graphs),
            "cache_misses": sum(int(graph.get("cache_misses", 0)) for graph in self.graphs),
            "run_count": sum(int(graph.get("run_count", 0)) for graph in self.graphs),
        }


@dataclass(frozen=True)
class _BuiltinCase:
    name: str
    fn: Any
    make_args: Any


def _builtin_add(x, y):
    return x + y


def _builtin_add_mul(x, y):
    return x + y * 2.0


def _builtin_three_input_chain(x, y, z):
    return x * 2.0 + y - z


def _builtin_scalar_alpha(x):
    return x + 2.5


def _builtin_two_scalars(x):
    return x * 2.5 + 1.25


def _builtin_relu_add(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.relu(x) + y


def _builtin_gelu(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.nn.functional.gelu(x)


def _builtin_silu(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.nn.functional.silu(x)


def _builtin_sigmoid_mul(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sigmoid(x) * y


def _builtin_tanh_shift(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.tanh(x) + 1.0


def _builtin_exp_log_abs(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.exp(torch.log(torch.abs(x) + 1.0))


def _builtin_sin_cos(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sin(x) + torch.cos(y)


def _builtin_where_cmp(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.where(x > y, x, y)


def _builtin_clamp_add(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.clamp(x, -0.5, 0.5) + y


def _builtin_reciprocal_abs(x):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.reciprocal(torch.abs(x) + 1.0)


def _builtin_sqrt_rsqrt(x, y):
    import torch  # pylint: disable=import-outside-toplevel

    return torch.sqrt(torch.abs(x) + 1.0) + torch.rsqrt(torch.abs(y) + 1.0)


def _builtin_pow2_add(x, y):
    return x * x + y


def _builtin_fp16_add(x, y):
    return x + y


def _builtin_bf16_add(x, y):
    return x + y


def _builtin_int32_add(x, y):
    return x + y


def _builtin_bool_mask(x, y):
    return (x > 0) & (y > 0)


def _builtin_broadcast_row(x, y):
    return x + y


def _builtin_broadcast_col(x, y):
    return x + y


def _builtin_tuple_two_outputs(x, y):
    return x + y, x - y


def _builtin_strided_input(x, y):
    return x[::2] + y


def _builtin_slice_even(x):
    return x[::2] * 2.0


def extract_inductor_triton_sources(
    wrapper_source: str,
    *,
    case_name: str = "",
    wrapper_path: str = "",
) -> list[InductorTritonSource]:
    """Extract ``async_compile.triton(name, source, ...)`` calls from wrapper code."""
    tree = ast.parse(wrapper_source)
    sources: list[InductorTritonSource] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not _is_triton_compile_call(node):
            continue
        if len(node.args) < 2:
            continue
        kernel_name = _literal_string(node.args[0])
        source = _literal_string(node.args[1])
        if not kernel_name or not source:
            continue
        device_str = "cuda"
        for keyword in node.keywords:
            if keyword.arg == "device_str":
                device_str = _literal_string(keyword.value) or device_str
        sources.append(
            InductorTritonSource(
                case_name=case_name or kernel_name,
                kernel_name=kernel_name,
                source=source,
                device_str=device_str,
                wrapper_path=wrapper_path,
            )
        )
    return sources


def extract_inductor_wrapper_extern_calls(
    wrapper_source: str,
    *,
    case_name: str = "",
    wrapper_path: str = "",
) -> list[InductorWrapperExternCall]:
    """Extract wrapper-level extern/ATen calls that are not Triton kernels."""
    tree = ast.parse(wrapper_source)
    lines = wrapper_source.splitlines()
    calls: list[InductorWrapperExternCall] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        op_name = _attribute_chain(node.func)
        op_family = _wrapper_extern_family(op_name)
        if not op_family:
            continue
        line_no = int(getattr(node, "lineno", 0) or 0)
        source_line = lines[line_no - 1].strip() if 0 < line_no <= len(lines) else ""
        calls.append(
            InductorWrapperExternCall(
                case_name=case_name,
                op_name=op_name,
                op_family=op_family,
                line_no=line_no,
                wrapper_path=wrapper_path,
                source=source_line,
            )
        )
    return sorted(calls, key=lambda call: (call.line_no, call.op_name))


def _attribute_chain(node: ast.AST) -> str:
    parts: list[str] = []
    current: ast.AST | None = node
    while isinstance(current, ast.Attribute):
        parts.append(current.attr)
        current = current.value
    if isinstance(current, ast.Name):
        parts.append(current.id)
    else:
        return ""
    return ".".join(reversed(parts))


def _wrapper_extern_family(op_name: str) -> str:
    if op_name in {"extern_kernels.mm", "extern_kernels.bmm"}:
        return "extern_gemm"
    if op_name == "extern_kernels.addmm":
        return "extern_addmm_bias"
    if op_name == "extern_kernels.convolution":
        return "deferred_convolution"
    if op_name == "torch.ops.aten._scaled_dot_product_efficient_attention.default":
        return "deferred_attention"
    return ""


def load_inductor_kernel(
    source: InductorTritonSource | str,
    *,
    kernel_name: str | None = None,
    case_name: str = "",
    device_str: str = "cuda",
) -> InductorKernel:
    """Load an Inductor Triton source block through PyTorch's ``PyCodeCache``."""
    if isinstance(source, InductorTritonSource):
        kernel_name = source.kernel_name
        case_name = source.case_name
        device_str = source.device_str
        source_code = source.source
    else:
        source_code = source
        kernel_name = kernel_name or _first_triton_jit_function_name(source_code)
        case_name = case_name or kernel_name

    if not kernel_name:
        raise ValueError("Cannot load Inductor Triton source without a kernel name")

    from torch._inductor.codecache import PyCodeCache  # pylint: disable=import-outside-toplevel

    key, path = PyCodeCache.write(source_code)
    module = PyCodeCache.load_by_key_path(key, path, attrs={})
    kernel = getattr(module, kernel_name)
    triton_meta = dict(getattr(kernel, "triton_meta", {}) or {})
    inductor_meta = dict(getattr(kernel, "inductor_meta", {}) or {})
    configs = list(getattr(kernel, "configs", []) or [])
    constexprs = dict(getattr(configs[0], "kwargs", {}) if configs else {})
    signature = dict(triton_meta.get("signature", {}) or {})
    attrs = None
    if configs and hasattr(kernel, "_create_compile_meta"):
        compile_meta = kernel._create_compile_meta(configs[0])  # pylint: disable=protected-access
        signature = dict(compile_meta.get("signature", signature))
        constexprs = dict(compile_meta.get("constants", constexprs))
        attrs = compile_meta.get("configs", [None])[0]

    return InductorKernel(
        case_name=case_name,
        kernel_name=kernel_name,
        source=source_code,
        device_str=device_str,
        fn=getattr(kernel, "fn", kernel),
        signature=signature,
        constexprs=constexprs,
        attrs=attrs,
        triton_meta=triton_meta,
        inductor_meta=inductor_meta,
        size_hints=dict(getattr(kernel, "size_hints", {}) or {}),
    )


def is_inductor_pointwise_kernel(kernel: InductorKernel) -> bool:
    """Return whether a loaded kernel matches the M3 pointwise audit filter."""
    meta = kernel.inductor_meta
    return (
        "triton_heuristics.pointwise" in kernel.source
        and meta.get("grid_type") == "Grid1D"
        and int(meta.get("num_reduction", 0) or 0) == 0
        and not bool(meta.get("atomic_add_found", False))
    )


def lower_inductor_kernel_to_ttir(
    kernel: InductorKernel,
    *,
    dump_path: str | Path | None = None,
) -> TTIRArtifact:
    """Lower a loaded Inductor Triton kernel to optimized TTIR."""
    if kernel.device_str == "cuda":
        from torch._inductor.runtime import (  # pylint: disable=import-outside-toplevel
            triton_helpers,
        )

        triton_helpers.set_driver_to_gpu()
    return lower_to_ttir(
        kernel.fn,
        kernel.signature,
        kernel.constexprs,
        dump_path=dump_path,
        attrs=kernel.attrs,
    )


def make_triton_tvm_inductor_backend(
    config: TritonTVMInductorConfig | TritonTVMInductorSession | None = None,
):
    """Return an experimental backend callable for ``torch.compile``.

    The returned object has a ``triton_tvm_session`` attribute so tests and
    debugging tools can inspect reports and the process-local artifact cache.
    """
    if isinstance(config, TritonTVMInductorSession):
        session = config
    else:
        session = TritonTVMInductorSession(config or TritonTVMInductorConfig())

    def triton_tvm_inductor_backend(model_, example_inputs_, **kwargs):
        try:
            import torch  # pylint: disable=import-outside-toplevel
            import triton  # pylint: disable=import-outside-toplevel
            from torch._inductor.async_compile import (  # pylint: disable=import-outside-toplevel
                AsyncCompile,
            )
            import torch._inductor.compile_fx as compile_fx_mod  # pylint: disable=import-outside-toplevel

            session._record_private_api_guard(  # pylint: disable=protected-access
                _validate_torch_inductor_private_api(
                    torch_module=torch,
                    compile_fx=compile_fx_mod.compile_fx,
                    triton_module=triton,
                )
            )
            original_triton = _install_async_compile_triton_hook(AsyncCompile, session)
        except ImportError as err:
            guard_err = ValueError(
                "triton_tvm_inductor_private_api_guard: PyTorch, TorchInductor, "
                f"and Triton must be importable before installing the hook: {err}"
            )
            _record_private_api_guard_error_once(session, guard_err)
            raise guard_err from err
        except Exception as err:
            _record_private_api_guard_error_once(session, err)
            raise

        graph = session.begin_graph(
            compile_region_name=str(kwargs.get("compile_region_name", ""))
        )
        try:
            result = compile_fx_mod.compile_fx(model_, example_inputs_, **kwargs)
        except Exception as err:
            session.end_graph(graph, ok=False, err=err)
            raise
        else:
            session.end_graph(graph, ok=True)
            return result
        finally:
            _restore_async_compile_triton_hook(AsyncCompile, original_triton)

    triton_tvm_inductor_backend.__name__ = "triton_tvm_inductor_backend"
    triton_tvm_inductor_backend.triton_tvm_session = session
    return triton_tvm_inductor_backend


def _install_async_compile_triton_hook(async_compile_cls, session: TritonTVMInductorSession):
    global _ACTIVE_HOOK  # pylint: disable=global-statement

    try:
        session._record_private_api_guard(  # pylint: disable=protected-access
            _validate_async_compile_triton_api(async_compile_cls)
        )
    except Exception as err:
        _record_private_api_guard_error_once(session, err)
        raise

    _HOOK_LOCK.acquire()
    original_triton = async_compile_cls.triton
    if _ACTIVE_HOOK is not None or getattr(original_triton, "_triton_tvm_hook", False):
        _HOOK_LOCK.release()
        raise RuntimeError(
            "triton_tvm_inductor_hook_reentrant_compile: AsyncCompile.triton is "
            "already patched by an active Triton TVM Inductor session"
        )

    def patched_triton(async_compile, kernel_name, source_code, device_str="cuda"):
        return session.compile_triton(
            async_compile,
            original_triton,
            kernel_name,
            source_code,
            device_str,
        )

    patched_triton._triton_tvm_hook = True  # type: ignore[attr-defined]
    _ACTIVE_HOOK = {"session": session, "original_triton": original_triton}
    async_compile_cls.triton = patched_triton
    return original_triton


def _restore_async_compile_triton_hook(async_compile_cls, original_triton) -> None:
    global _ACTIVE_HOOK  # pylint: disable=global-statement

    try:
        async_compile_cls.triton = original_triton
        _ACTIVE_HOOK = None
    finally:
        _HOOK_LOCK.release()


def _validate_torch_inductor_private_api(
    *,
    torch_module,
    compile_fx,
    triton_module,
) -> dict[str, Any]:
    torch_compile = getattr(torch_module, "compile", None)
    if not callable(torch_compile):
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: torch.compile must be callable"
        )
    if not callable(compile_fx):
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: torch._inductor.compile_fx.compile_fx "
            "must be callable"
        )

    torch_version = str(getattr(torch_module, "__version__", ""))
    triton_version = str(getattr(triton_module, "__version__", ""))
    if not torch_version or not triton_version:
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: torch and triton versions must "
            f"be discoverable, got torch={torch_version!r}, triton={triton_version!r}"
        )

    return {
        "torch_compile": "callable",
        "torch_inductor_compile_fx": "callable",
        "torch_version": torch_version,
        "torch_inductor_version": torch_version,
        "triton_version": triton_version,
    }


def _validate_async_compile_triton_api(async_compile_cls) -> dict[str, Any]:
    original_triton = getattr(async_compile_cls, "triton", None)
    if not callable(original_triton):
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: AsyncCompile.triton must be callable"
        )
    try:
        signature = inspect.signature(original_triton)
    except (TypeError, ValueError) as err:
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: AsyncCompile.triton must expose "
            "an inspectable Python signature"
        ) from err
    try:
        signature.bind(object(), "kernel_name", "source_code", "cuda")
    except TypeError as err:
        raise ValueError(
            "triton_tvm_inductor_private_api_guard: AsyncCompile.triton signature "
            "must accept (async_compile, kernel_name, source_code, device_str)"
        ) from err
    return {"async_compile_triton_signature": str(signature)}


def _record_private_api_guard_error_once(
    session: TritonTVMInductorSession,
    err: Exception,
) -> None:
    if getattr(err, "_triton_tvm_guard_recorded", False):
        return
    session._record_private_api_guard_error(err)  # pylint: disable=protected-access
    try:
        setattr(err, "_triton_tvm_guard_recorded", True)
    except Exception:  # pylint: disable=broad-except
        pass


class _TritonTVMInductorKernel:
    def __init__(
        self,
        *,
        session: TritonTVMInductorSession,
        record: dict[str, Any],
        artifact: TritonTVMArtifact,
        async_compile,
        original_triton,
        kernel_name: str,
        source_code: str,
        device_str: str,
    ):
        self.session = session
        self.record = record
        self.artifact = artifact
        self.async_compile = async_compile
        self.original_triton = original_triton
        self.kernel_name = kernel_name
        self.source_code = source_code
        self.device_str = device_str

    def run(  # pylint: disable=unused-argument
        self,
        *args,
        stream,
        benchmark_run=False,
        **kwargs,
    ):
        """Launch the TVM artifact using PyTorch tensors and Inductor's raw stream."""
        try:
            if kwargs:
                raise ValueError(
                    "M5 Triton TVM Inductor launcher does not support keyword "
                    f"runtime arguments: {sorted(kwargs)}"
                )
            tvm_args, device_index = _torch_runtime_args_to_tvm(
                args, self.artifact.meta
            )
            dev = _tvm_cuda_device(device_index)
            if stream is not None:
                dev.set_raw_stream(int(stream))
            try:
                result = self.artifact.run(tvm_args)
            finally:
                if stream is not None:
                    dev.set_raw_stream(0)
        except Exception as err:  # pylint: disable=broad-except
            status = status_from_exception(err)
            self.record["runtime_status"] = status
            self.record["translate_status"] = status
            self.record["native_fallback_count"] = self.record.get("native_fallback_count", 0)
            self.session.counters["runtime_errors"] += 1
            self.session.write_report()
            raise

        self.session._record_run(self.record)  # pylint: disable=protected-access
        return result


def audit_inductor_ttir(
    ttir_or_artifact: str | TTIRArtifact,
    *,
    case_name: str = "",
    kernel_name: str = "",
    source: str = "",
    signature: dict[str, str] | None = None,
    constexprs: dict[str, Any] | None = None,
    contract: str = "pointwise_flat",
) -> dict[str, Any]:
    """Summarize one Inductor TTIR module and classify translator support."""
    if isinstance(ttir_or_artifact, TTIRArtifact):
        ttir = ttir_or_artifact.ttir
        kernel_name = kernel_name or ttir_or_artifact.kernel_name
        signature = signature or ttir_or_artifact.signature
        constexprs = constexprs or ttir_or_artifact.constexprs
    else:
        ttir = ttir_or_artifact

    record: dict[str, Any] = {
        "corpus": "m3_inductor_pointwise",
        "case_name": case_name or kernel_name,
        "kernel_name": kernel_name,
        "contract": contract,
        "source_hash": _sha256(source) if source else "",
        "ttir_hash": _sha256(ttir),
        "signature": dict(signature or {}),
        "constexprs": _jsonable(dict(constexprs or {})),
        "unique_ops": [],
        "op_counts": {},
        "types": [],
        "raw_load_store_attrs": [],
        "load_count": 0,
        "store_count": 0,
        "mask_forms": [],
        "indexing_summary": {},
        "translate_status": {"ok": False, "bucket": "not_run"},
    }

    try:
        graph = TTIRReader().read(ttir)
    except Exception as err:  # pylint: disable=broad-except
        record["translate_status"] = _error_status("reader_error", err)
        return record

    record.update(_graph_coverage(graph))
    try:
        translate_ttir(ttir, grid=(1,), contract=contract)
        record["translate_status"] = make_report_status(ok=True, bucket="translated")
    except UnsupportedTTIROpError as err:
        record["translate_status"] = _error_status("unsupported_ttir_op", err)
    except (TritonTVMContractError, UnsupportedContractError) as err:
        record["translate_status"] = _error_status("contract_error", err)
    except UnsupportedTargetPolicyError as err:
        record["translate_status"] = _error_status("target_policy_error", err)
    except Exception as err:  # pylint: disable=broad-except
        record["translate_status"] = _error_status("translate_other_error", err)
    return record


def audit_inductor_kernel(
    kernel: InductorKernel,
    *,
    ttir_dir: str | Path | None = None,
    contract: str = "pointwise_flat",
) -> dict[str, Any]:
    """Lower and audit a loaded Inductor pointwise kernel."""
    dump_path = None
    if ttir_dir is not None:
        dump_path = Path(ttir_dir) / f"{_safe_name(kernel.case_name)}_{kernel.kernel_name}.ttir"
    try:
        artifact = lower_inductor_kernel_to_ttir(kernel, dump_path=dump_path)
    except Exception as err:  # pylint: disable=broad-except
        return {
            "corpus": "m3_inductor_pointwise",
            "case_name": kernel.case_name,
            "kernel_name": kernel.kernel_name,
            "contract": contract,
            "source_hash": _sha256(kernel.source),
            "ttir_hash": "",
            "signature": dict(kernel.signature),
            "constexprs": _jsonable(kernel.constexprs),
            "unique_ops": [],
            "op_counts": {},
            "types": [],
            "raw_load_store_attrs": [],
            "load_count": 0,
            "store_count": 0,
            "mask_forms": [],
            "indexing_summary": {},
            "translate_status": _error_status("lowering_error", err),
        }
    return audit_inductor_ttir(
        artifact,
        case_name=kernel.case_name,
        kernel_name=kernel.kernel_name,
        source=kernel.source,
        signature=kernel.signature,
        constexprs=kernel.constexprs,
        contract=contract,
    )


def run_inductor_audit(
    sources: list[InductorTritonSource],
    *,
    out_dir: str | Path,
    min_kernels: int = 20,
    contract: str = "pointwise_flat",
    extra_errors: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Audit extracted Inductor sources and write kernel, TTIR, and report files."""
    out_path = Path(out_dir)
    kernel_dir = out_path / "kernels"
    ttir_dir = out_path / "ttir"
    kernel_dir.mkdir(parents=True, exist_ok=True)
    ttir_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    filtered: list[dict[str, Any]] = []
    errors = list(extra_errors or [])

    for source in sources:
        kernel_path = kernel_dir / f"{_safe_name(source.case_name)}_{source.kernel_name}.py"
        kernel_path.write_text(source.source, encoding="utf-8")
        try:
            kernel = load_inductor_kernel(source)
        except Exception as err:  # pylint: disable=broad-except
            errors.append(
                {
                    "case_name": source.case_name,
                    "kernel_name": source.kernel_name,
                    "bucket": "load_error",
                    "error_type": type(err).__name__,
                    "message": str(err),
                }
            )
            continue
        if not is_inductor_pointwise_kernel(kernel):
            filtered.append(
                {
                    "case_name": kernel.case_name,
                    "kernel_name": kernel.kernel_name,
                    "grid_type": kernel.inductor_meta.get("grid_type"),
                    "num_reduction": kernel.inductor_meta.get("num_reduction"),
                    "atomic_add_found": kernel.inductor_meta.get("atomic_add_found"),
                }
            )
            continue
        record = audit_inductor_kernel(kernel, ttir_dir=ttir_dir, contract=contract)
        record["kernel_source_path"] = str(kernel_path)
        ttir_path = ttir_dir / f"{_safe_name(kernel.case_name)}_{kernel.kernel_name}.ttir"
        record["ttir_path"] = str(ttir_path)
        records.append(record)

    if len(records) < min_kernels:
        raise RuntimeError(
            f"M3 Inductor audit collected {len(records)} pointwise kernels, "
            f"below required minimum {min_kernels}"
        )

    report = build_audit_report(records, filtered=filtered, errors=errors)
    write_audit_report(report, out_path)
    return report


def build_audit_report(
    kernel_records: list[dict[str, Any]],
    *,
    filtered: list[dict[str, Any]] | None = None,
    errors: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build the JSON-serializable M3 audit report payload."""
    records = []
    for record in kernel_records:
        normalized = dict(record)
        normalized.setdefault("corpus", "m3_inductor_pointwise")
        normalized.setdefault("contract", "")
        records.append(normalized)
    return build_capability_report(
        records,
        purpose="m3 inductor pointwise ttir coverage audit",
        corpus="m3_inductor_pointwise",
        filtered=filtered,
        errors=errors,
    )


def write_audit_report(report: dict[str, Any], out_dir: str | Path) -> None:
    """Write ``report.json`` and ``report.md`` for an M3 audit run."""
    write_capability_report(
        report,
        out_dir,
        markdown_title="M3 Inductor Pointwise TTIR Audit",
        footer_lines=_pre_m5_boundary_lines(),
    )


def render_audit_markdown(report: dict[str, Any]) -> str:
    """Render a compact Markdown view of the M3 audit report."""
    return render_capability_markdown(
        report,
        title="M3 Inductor Pointwise TTIR Audit",
        footer_lines=_pre_m5_boundary_lines(),
    )


def _pre_m5_boundary_lines() -> list[str]:
    return [
        "## Pre-M5 Boundary",
        "",
        "- Keep this audit offline-only until the M5 hook owns launcher/cache/fallback.",
        "- Route supported pointwise capability through canonical `pointwise_flat`.",
        "- Keep unsupported kernels in stable report buckets with `fallback_reason`.",
    ]


def collect_builtin_inductor_sources(
    *,
    min_kernels: int = 20,
) -> tuple[list[InductorTritonSource], list[dict[str, Any]]]:
    """Compile the built-in pointwise corpus and collect generated Triton sources."""
    import torch  # pylint: disable=import-outside-toplevel
    import torch._dynamo  # pylint: disable=import-outside-toplevel
    import torch._inductor.config as inductor_config  # pylint: disable=import-outside-toplevel
    from torch._inductor.graph import GraphLowering  # pylint: disable=import-outside-toplevel

    if not torch.cuda.is_available():
        raise RuntimeError("The built-in Inductor corpus requires CUDA")

    old_save_output_code = GraphLowering.save_output_code
    old_fx_graph_cache = inductor_config.fx_graph_cache
    sources: list[InductorTritonSource] = []
    errors: list[dict[str, Any]] = []
    inductor_config.fx_graph_cache = False
    try:
        builtin_module = _load_builtin_corpus_module()
        for case in _builtin_cases(torch, builtin_module):
            captured: list[str] = []
            GraphLowering.save_output_code = captured.append
            try:
                torch._dynamo.reset()
                compiled = torch.compile(case.fn, backend="inductor")
                args = case.make_args(torch)
                with torch.no_grad():
                    compiled(*args)
                torch.cuda.synchronize()
            except Exception as err:  # pylint: disable=broad-except
                errors.append(
                    {
                        "case_name": case.name,
                        "kernel_name": "",
                        "bucket": "compile_error",
                        "error_type": type(err).__name__,
                        "message": str(err),
                    }
                )
            finally:
                GraphLowering.save_output_code = old_save_output_code
            for wrapper_source in captured:
                sources.extend(
                    extract_inductor_triton_sources(wrapper_source, case_name=case.name)
                )
    finally:
        GraphLowering.save_output_code = old_save_output_code
        inductor_config.fx_graph_cache = old_fx_graph_cache
        torch._dynamo.reset()

    if len(sources) < min_kernels:
        errors.append(
            {
                "case_name": "builtin_corpus",
                "kernel_name": "",
                "bucket": "collection_error",
                "error_type": "RuntimeError",
                "message": f"collected {len(sources)} Triton sources below requested {min_kernels}",
            }
        )
    return sources, errors


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for ``python -m tvm.contrib.triton_tvm.inductor``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--builtin-corpus", action="store_true")
    parser.add_argument("--input-dir", type=Path, action="append", default=[])
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--min-kernels", type=int, default=20)
    parser.add_argument("--contract", default="pointwise_flat")
    args = parser.parse_args(argv)

    sources: list[InductorTritonSource] = []
    errors: list[dict[str, Any]] = []
    if args.builtin_corpus:
        builtin_sources, builtin_errors = collect_builtin_inductor_sources(
            min_kernels=args.min_kernels
        )
        sources.extend(builtin_sources)
        errors.extend(builtin_errors)
    for input_dir in args.input_dir:
        sources.extend(_sources_from_input_dir(input_dir))
    if not sources:
        raise RuntimeError("No Inductor Triton sources were collected")

    report = run_inductor_audit(
        sources,
        out_dir=args.out_dir,
        min_kernels=args.min_kernels,
        contract=args.contract,
        extra_errors=errors,
    )
    print(
        "Wrote M3 Inductor audit with "
        f"{report['total_kernels']} kernels to {args.out_dir}"
    )
    return 0


def _sources_from_input_dir(input_dir: Path) -> list[InductorTritonSource]:
    sources: list[InductorTritonSource] = []
    for path in sorted(input_dir.rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        sources.extend(
            extract_inductor_triton_sources(
                text,
                case_name=path.stem,
                wrapper_path=str(path),
            )
        )
    return sources


def _graph_coverage(graph: NormalizedTTIROpGraph) -> dict[str, Any]:
    op_counts = Counter(op.name for op in graph.ops)
    types = sorted(
        {
            param.type.raw
            for param in graph.params
        }
        | {
            ty.raw
            for op in graph.ops
            for ty in op.result_types
        }
    )
    load_store_attrs = []
    for op in graph.ops:
        if op.name in ("tt.load", "tt.store") and op.attrs.get("raw_attrs"):
            load_store_attrs.append(
                {
                    "op": op.name,
                    "raw_attrs": op.attrs.get("raw_attrs", ""),
                    "unknown_attrs": dict(op.attrs.get("unknown_attrs", {}) or {}),
                }
            )
    return {
        "unique_ops": sorted(op_counts),
        "op_counts": dict(sorted(op_counts.items())),
        "types": types,
        "raw_load_store_attrs": load_store_attrs,
        "load_count": op_counts.get("tt.load", 0),
        "store_count": op_counts.get("tt.store", 0),
        "mask_forms": _mask_forms(graph),
        "indexing_summary": _indexing_summary(graph),
    }


def _mask_forms(graph: NormalizedTTIROpGraph) -> list[dict[str, str]]:
    defs = graph.op_by_result()
    forms: list[dict[str, str]] = []
    seen: set[tuple[str, str, str]] = set()
    for op in graph.ops:
        mask = ""
        if op.name == "tt.load" and len(op.operands) >= 2:
            mask = op.operands[1]
        elif op.name == "tt.store" and len(op.operands) >= 3:
            mask = op.operands[2]
        if not mask:
            continue
        mask_def = defs.get(mask)
        key = (op.name, mask, mask_def.raw if mask_def else "")
        if key in seen:
            continue
        seen.add(key)
        forms.append(
            {
                "consumer": op.name,
                "mask": mask,
                "def_op": mask_def.name if mask_def else "",
                "raw": mask_def.raw if mask_def else "",
            }
        )
    return forms


def _indexing_summary(graph: NormalizedTTIROpGraph) -> dict[str, Any]:
    program_id_axes = [
        str(op.attrs.get("axis", ""))
        for op in graph.ops
        if op.name == "tt.get_program_id"
    ]
    addptr_ops = [op for op in graph.ops if op.name == "tt.addptr"]
    summary = {
        "kind": "flat_or_broadcast_candidate" if addptr_ops else "no_addptr",
        "addptr_count": len(addptr_ops),
        "make_range_count": sum(1 for op in graph.ops if op.name == "tt.make_range"),
        "program_id_axes": sorted(set(program_id_axes)),
        "addptr_operands": [list(op.operands) for op in addptr_ops],
    }
    summary.update(summarize_ttir_indexing(graph))
    return summary


def _load_builtin_corpus_module():
    source = textwrap.dedent(
        """
        import torch

        def m3_add(x, y):
            return x + y

        def m3_add_mul(x, y):
            return x + y * 2.0

        def m3_three_input_chain(x, y, z):
            return x * 2.0 + y - z

        def m3_scalar_alpha(x):
            return x + 2.5

        def m3_two_scalars(x):
            return x * 2.5 + 1.25

        def m3_relu_add(x, y):
            return torch.relu(x) + y

        def m3_gelu(x):
            return torch.nn.functional.gelu(x)

        def m3_silu(x):
            return torch.nn.functional.silu(x)

        def m3_sigmoid_mul(x, y):
            return torch.sigmoid(x) * y

        def m3_tanh_shift(x):
            return torch.tanh(x) + 1.0

        def m3_exp_log_abs(x):
            return torch.exp(torch.log(torch.abs(x) + 1.0))

        def m3_sin_cos(x, y):
            return torch.sin(x) + torch.cos(y)

        def m3_where_cmp(x, y):
            return torch.where(x > y, x, y)

        def m3_clamp_add(x, y):
            return torch.clamp(x, -0.5, 0.5) + y

        def m3_reciprocal_abs(x):
            return torch.reciprocal(torch.abs(x) + 1.0)

        def m3_sqrt_rsqrt(x, y):
            return torch.sqrt(torch.abs(x) + 1.0) + torch.rsqrt(torch.abs(y) + 1.0)

        def m3_pow2_add(x, y):
            return x * x + y

        def m3_fp16_add(x, y):
            return x + y

        def m3_bf16_add(x, y):
            return x + y

        def m3_int32_add(x, y):
            return x + y

        def m3_bool_mask(x, y):
            return (x > 0) & (y > 0)

        def m3_broadcast_row(x, y):
            return x + y

        def m3_broadcast_col(x, y):
            return x + y

        def m3_tuple_two_outputs(x, y):
            return x + y, x - y

        def m3_strided_input(x, y):
            return x[::2] + y

        def m3_slice_even(x):
            return x[::2] * 2.0
        """
    )
    path = Path(tempfile.gettempdir()) / "triton_tvm_m3_builtin_corpus.py"
    path.write_text(source, encoding="utf-8")
    spec = importlib.util.spec_from_file_location("triton_tvm_m3_builtin_corpus", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import builtin corpus module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _builtin_cases(torch, module=None) -> list[_BuiltinCase]:
    device = "cuda"

    def rand(shape, dtype=torch.float32):
        return torch.randn(shape, device=device, dtype=dtype)

    def randint(shape):
        return torch.randint(0, 17, shape, device=device, dtype=torch.int32)

    def fn(name: str):
        if module is not None:
            return getattr(module, f"m3_{name}")
        return globals()[f"_builtin_{name}"]

    return [
        _BuiltinCase("add", fn("add"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase("add_mul", fn("add_mul"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase(
            "three_input_chain",
            fn("three_input_chain"),
            lambda _: (rand((257,)), rand((257,)), rand((257,))),
        ),
        _BuiltinCase("scalar_alpha", fn("scalar_alpha"), lambda _: (rand((256,)),)),
        _BuiltinCase("two_scalars", fn("two_scalars"), lambda _: (rand((256,)),)),
        _BuiltinCase(
            "relu_add",
            fn("relu_add"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase("gelu", fn("gelu"), lambda _: (rand((256,)),)),
        _BuiltinCase("silu", fn("silu"), lambda _: (rand((256,)),)),
        _BuiltinCase(
            "sigmoid_mul",
            fn("sigmoid_mul"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase("tanh_shift", fn("tanh_shift"), lambda _: (rand((256,)),)),
        _BuiltinCase(
            "exp_log_abs",
            fn("exp_log_abs"),
            lambda _: (rand((256,)),),
        ),
        _BuiltinCase(
            "sin_cos",
            fn("sin_cos"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "where_cmp",
            fn("where_cmp"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "clamp_add",
            fn("clamp_add"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "reciprocal_abs",
            fn("reciprocal_abs"),
            lambda _: (rand((256,)),),
        ),
        _BuiltinCase(
            "sqrt_rsqrt",
            fn("sqrt_rsqrt"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase("pow2_add", fn("pow2_add"), lambda _: (rand((256,)), rand((256,)))),
        _BuiltinCase(
            "fp16_add",
            fn("fp16_add"),
            lambda _: (rand((256,), torch.float16), rand((256,), torch.float16)),
        ),
        _BuiltinCase(
            "bf16_add",
            fn("bf16_add"),
            lambda _: (rand((256,), torch.bfloat16), rand((256,), torch.bfloat16)),
        ),
        _BuiltinCase("int32_add", fn("int32_add"), lambda _: (randint((256,)), randint((256,)))),
        _BuiltinCase(
            "bool_mask",
            fn("bool_mask"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "broadcast_row",
            fn("broadcast_row"),
            lambda _: (rand((16, 16)), rand((1, 16))),
        ),
        _BuiltinCase(
            "broadcast_col",
            fn("broadcast_col"),
            lambda _: (rand((16, 16)), rand((16, 1))),
        ),
        _BuiltinCase(
            "tuple_two_outputs",
            fn("tuple_two_outputs"),
            lambda _: (rand((256,)), rand((256,))),
        ),
        _BuiltinCase(
            "strided_input",
            fn("strided_input"),
            lambda _: (rand((512,)), rand((256,))),
        ),
        _BuiltinCase("slice_even", fn("slice_even"), lambda _: (rand((512,)),)),
    ]


def _is_triton_compile_call(node: ast.Call) -> bool:
    return isinstance(node.func, ast.Attribute) and node.func.attr == "triton"


def _literal_string(node: ast.AST) -> str:
    try:
        value = ast.literal_eval(node)
    except (ValueError, SyntaxError):
        return ""
    return value if isinstance(value, str) else ""


def _first_triton_jit_function_name(source: str) -> str:
    tree = ast.parse(source)
    saw_jit = False
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if any(_decorator_mentions_triton_jit(decorator) for decorator in node.decorator_list):
            return node.name
    return ""


def _decorator_mentions_triton_jit(node: ast.AST) -> bool:
    if isinstance(node, ast.Attribute) and node.attr == "jit":
        return True
    if isinstance(node, ast.Call):
        return _decorator_mentions_triton_jit(node.func)
    return False


def _torch_runtime_args_to_tvm(args: tuple[Any, ...], meta) -> tuple[list[Any], int]:
    import tvm  # pylint: disable=import-outside-toplevel

    if len(args) != len(meta.abi):
        raise ValueError(f"Expected {len(meta.abi)} runtime arguments, got {len(args)}")

    tvm_args: list[Any] = []
    device_index = 0
    for arg, spec in zip(args, meta.abi, strict=True):
        if spec["kind"] == "pointer":
            device = getattr(arg, "device", None)
            if getattr(device, "type", None) == "cuda" and device.index is not None:
                device_index = int(device.index)
            tvm_args.append(tvm.runtime.from_dlpack(arg))
        else:
            tvm_args.append(arg)
    return tvm_args, device_index


def _tvm_cuda_device(device_index: int):
    import tvm  # pylint: disable=import-outside-toplevel

    return tvm.cuda(device_index)


def _base_m5_record(
    *,
    kernel_name: str,
    source: str,
    signature: dict[str, str],
    constexprs: dict[str, Any],
    status: dict[str, Any],
) -> dict[str, Any]:
    return {
        "corpus": "m5_inductor_hook",
        "case_name": kernel_name,
        "kernel_name": kernel_name,
        "contract": "pointwise_flat",
        "source_hash": _sha256(source),
        "ttir_hash": "",
        "signature": dict(signature),
        "constexprs": _jsonable(dict(constexprs)),
        "unique_ops": [],
        "op_counts": {},
        "types": [],
        "raw_load_store_attrs": [],
        "load_count": 0,
        "store_count": 0,
        "mask_forms": [],
        "indexing_summary": {},
        "cache_key": "",
        "cache_hit": False,
        "run_count": 0,
        "native_fallback_count": 0,
        "translate_status": status,
    }


def _m5_boundary_lines() -> list[str]:
    return [
        "## M5 / Pre-M6 Boundary",
        "",
        "- Experimental `torch.compile` backend; no stable Inductor ABI is promised.",
        "- Supported `pointwise_flat` kernels run through TVM.",
        "- Unsupported kernels use explicit native Triton fallback by default.",
        "- Disk cache remains disabled; artifact cache is process-local.",
        "- Markdown shows graph summaries; JSON remains authoritative for graph details.",
    ]


def _m5_runtime_counter_policy() -> dict[str, str]:
    return {
        "run_count": "successful_tvm_launcher_calls_only",
        "native_fallback_count": "compile_time_native_fallback_decisions_only",
    }


def _error_status(bucket: str, err: Exception) -> dict[str, Any]:
    return make_report_status(
        ok=False,
        bucket=bucket,
        error_type=type(err).__name__,
        message=str(err),
    )


def _jsonable(value: Any) -> Any:
    try:
        json.dumps(value)
        return value
    except TypeError:
        if isinstance(value, dict):
            return {str(k): _jsonable(v) for k, v in value.items()}
        if isinstance(value, (list, tuple, set, frozenset)):
            return [_jsonable(v) for v in value]
        return repr(value)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _safe_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in name)


if __name__ == "__main__":
    raise SystemExit(main())
